kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "nodejs-example"
  annotations:
    description: Defines how to build the application
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/sclorg/nodejs-ex.git"
      ref: 
    contextDir: 
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/nodejs-10:latest
      env:
      - name: NPM_MIRROR
        value: 
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-example:latest
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secret: "cS3AFvpd1DLz7C0VW5OVmJhTnXM0qwuOy4JFtulV"
  - type: Generic
    generic:
      secret: "gUE5VbKpAmDhz0dYMx5VkZUGK31jQxgE2uOfazNv"
  postCommit:
    script: npm test
