apiVersion: v1
appVersion: 1.2.15
description: Shared Configurable Helpers (SCH)
keywords:
- Commercial
- Limited
- utility
- ibm-samples
- amd64
- ppc64le
- s390x
kubeVersion: '>=1.11.0'
name: ibm-sch
version: 1.2.15
